name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Configurar topics académicos
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/topics \
            -f names[]=campus-juliaca \
            -f names[]=linea-software \
            -f names[]=curso-distribuidas \
            -f names[]=grupo-gu \
            -f names[]=equipo-thereeds

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force